### ISSUE TITLE
Enable caching even when the workflow failed

### ISSUE THREAD

**Issue by jmoguillansky-gpsw** [actions/cache#541] opened 2021-02-19 20:35 UTC
It would be helpful if there was an option to save the data to the cache even if the workflow failed.  There can be a user function to explicitly save to the cache.  
For example suppose that we restore some dependencies from cache, and if cache miss build the dependencies , then build the project, then afterwards cache the dependencies.  If building the dependencies passes but building the project fails, then we have to start all over the next run and build the dependencies

**Comment by jmoguillansky-gpsw** [comment] 2021-03-11 01:33
In action.yaml: can we let the user customize "post-if", for example, post-if: steps.xyz.sucess()

runs:
  using: 'node12'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
  post-if: 'success()'

**Comment by dhadka** [comment] 2021-03-11 03:24
I don't think users can modify the post-if without forking this repo.  However, it's possible to use an env var that is set when the desired step is successful.  For example, see this PR using an env var to skip the post step - https://github.com/actions/cache/pull/489.

**Comment by eyal0** [comment] 2021-03-25 19:49
Maybe this? https://github.com/actions/cache/pull/498

**Comment by konradpabjan** [comment] 2021-04-29 22:16
Closing as a duplicate of: https://github.com/actions/cache/issues/272

**Closed by konradpabjan** 2021-04-29 22:16 UTC
Labels: duplicate
