### ISSUE TITLE
Post action prevents cache from saving, build still passes

### ISSUE THREAD

**Issue by evancloutier** [actions/cache#111] opened 2019-11-21 16:15 UTC
Trying to move over my Rails app from CircleCI, and the last step I'm stuck with is caching my dependencies.

It looks like my workflow cannot find `vendor/bundle` causing a warning (but the build itself still passes) and a program exit.

```bash
Post job cleanup.
/bin/tar -cz -f /home/runner/work/_temp/e63e7a43-36d8-40ef-8981-8fcdfedfce0f/cache.tgz -C /home/runner/work/ivy-service/ivy-service/vendor/bundle .
/bin/tar: /home/runner/work/ivy-service/ivy-service/vendor/bundle: Cannot open: No such file or directory
/bin/tar: Error is not recoverable: exiting now
##[warning]The process '/bin/tar' failed with exit code 2
```

If this is failing to save the cache -- shouldn't this build be failing and not passing with a warning? There will always be a cache miss, causing my workflow to re-install gems, and eventual failure.

I'm not sure if I'm looking for bundle in the wrong spot, as I'm using the example from the documentation:

```
- uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
```

**Comment by dhadka** [comment] 2019-11-21 21:20
Hi @evancloutier, I suspect the gems are stored in a different location.  If you look at how rails/rails is using the cache, they run `bundle config path vendor/bundle` (https://github.com/rails/rails/commit/55f9c8a147701f864602a16f0a6eb30054806b25) to set the path.  One advantage of this is it keeps the gems you're installing separate from whatever might come pre-installed on the image.  Please let us know if this works for you and we can update the documentation with this guidance.

> If this is failing to save the cache -- shouldn't this build be failing and not passing with a warning? There will always be a cache miss, causing my workflow to re-install gems, and eventual failure.

This is by design.  The cache action suppresses most, if not all, errors.  The idea is we don't want a caching issue to cause builds to fail.  Your build will take longer, but it won't fail.  In some cases, such as a configuration issue, one could argue that it should fail rather than warn, but this is the reasoning behind the behavior your see.

**Comment by dhadka** [comment] 2019-11-21 21:27
Yes, I think the documentation is missing a step.  I've opened a separate issue to update the documentation - https://github.com/actions/cache/issues/112.  Thanks for bringing this to our attention!

**Comment by evancloutier** [comment] 2019-11-21 23:25
@dhadka Great to know that the Rails project is using GH actions 🎉 

Your explanation for raising a warning makes sense -- thanks for that. Telling bundler the appropriate path fixed the issue, and the cache saved successfully. I'll follow up on your new issue and make a PR to update the documentation.

**Comment by dhadka** [comment] 2019-11-25 14:04
Closing.  Please open a new issue if you have any further questions or issues.

**Closed by dhadka** 2019-11-25 14:04 UTC
