### ISSUE TITLE
Warning: Cache service responded with 403

### ISSUE THREAD

**Issue by Bharani-Schawk** [actions/cache#478] opened 2020-12-04 05:37 UTC
Hello Team,

**Im getting "Warning: Cache service responded with 403"**. Its not caching the filepath as well.

Run actions/cache@v2
with:
path: /tmp/M2
  
key: Linux-webapp-build-m2-folder-cache-2785bfb041454a6cf71a9ef1f470ad37c54f89ac472600a3c22d2258ff1ea188
restore-keys: Linux-webapp-build-m2-folder-cache-
Linux-webapp-build-

**Comment by roziukp** [comment] 2021-01-05 21:21
have the same issue

**Comment by jorgegarciarey** [comment] 2021-01-19 17:19
Hi,
We have the same problem when a pull request is closed, for example:

![image](https://user-images.githubusercontent.com/59437749/105069627-81829880-5a82-11eb-8f56-fa3ae34040e3.png)

![image](https://user-images.githubusercontent.com/59437749/105069680-92330e80-5a82-11eb-8e30-60853e307584.png)

This warning only happens in events of type `closed` PR

**Comment by sergiocazzolato** [comment] 2021-01-27 20:21
I see the same problem using actions/cache@v1:
Warning: downloadCache failed: tunneling socket could not be established, statusCode=403

The self-hosted runner is running inside a lxd container and the proxy is properly set. I already checked the proxy settings and the log are showing neither denials nor 403

**Comment by catmeme** [comment] 2021-01-29 14:33
We're seeing this on `closed` `pull_request` as well.

**Comment by jorgegarciarey** [comment] 2021-01-31 10:11
Note that in my case, this warning appears in github hosted, for example: ubuntu-latest

**Comment by MarcosCela** [comment] 2021-02-04 09:37
We are seeing the same exact issue

**Comment by jfachal** [comment] 2021-02-04 13:28
same issue for us

**Comment by MarcosCela** [comment] 2021-02-26 11:05
You can easily reproduce the error with the following workflow file:


```yaml
name: test-cache-403
on:
  pull_request:
    types: [closed]
    branches: [main, master]



jobs:
  test-cache:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Output env
        run: env
      - name: Store cache
        uses: actions/cache@v2
        continue-on-error: true
        with:
          path: ~/.test/
          key: ${{ runner.os }}-test-
          restore-keys: |
            ${{ runner.os }}-test-
```

You need to create a PR and merge it to trigger the failure, the changed file does not matter.

***Possible explanation***

My understanding is that we are using the variable **GITHUB_REF** (which upon merging is "MASTER" or "MAIN", e.g: the branch where your changes are being merged to).
The problem appears to be that the workflow is associated with the source branch:
![image](https://user-images.githubusercontent.com/7879631/109292376-8fb69800-782a-11eb-8efa-6888c9de00da.png)


And the cache consistently returns a 403:

![image](https://user-images.githubusercontent.com/7879631/109292413-9e9d4a80-782a-11eb-87a3-f7f312836a0e.png)



What I understand is that:

- The cache action is trying to save the cache associated to the branch "master" (in my example).
- The cache run is associated with the origin branch, in my example: MarcosCela-patch-3
- The cache service returns a 403 because we are trying to save something to the master branch but we are running in the context of a different branch.


I might be completely wrong here tho, can anyone confirm?

**Comment by HartiganHM** [comment] 2021-02-26 19:24
We're having the same issue with `closed` type `pull_request` as well. We recently refactored to use this configuration without any other major changes.

**Comment by jgoux** [comment] 2021-03-11 09:27
We also have this issue through `bahmutov/npm-install@v1`, in our case it's erroring our action on the 403 error. Also on pull_request `closed` event.

**Comment by arthurrogel** [comment] 2021-03-23 00:10
We have the exact same behavior here. It's simply impossible to use this action in a closed PR event.

**Comment by sayduck-daniel** [comment] 2021-04-07 12:47
Same here.

**Comment by danielfn** [comment] 2021-05-19 10:02
FYI, we are no longed experiencing the 403 issue. Could someone else confirm this has been fixed?

**Comment by dhadka** [comment] 2021-05-19 15:29
@danielfn Yep, the fix for `pull_request` `closed` events has been rolled out.

**Closed by dhadka** 2021-05-19 15:29 UTC
