### ISSUE TITLE
Fails on tar exit code 1 on ubuntu-latest

### ISSUE THREAD

**Issue by cyberpwnn** [actions/cache#689] opened 2021-12-02 18:03 UTC
I need to share around a small but heavily processed repository to multiple jobs, 

```yml
    runs-on: ubuntu-latest
    steps: 
      - name: Cache Repository
        uses: actions/cache@v2
        with:
          path: |
            ~/
            !~/.git/
```

Fails with

```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/xxx/xxx--files-from manifest.txt
/usr/bin/tar: ../../../work/_temp/6483fbb9-3579-4fb0-a582-3316b336d5a9/cache.tzst: file changed as we read it
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 1
```

**Comment by vsvipul** [comment] 2021-12-21 11:24
Hi @cyberpwnn ! Is this repo public? If yes, can you share link to the workflow run. If not, can you share the logs here?

**Comment by MatthieuLeboeuf** [comment] 2021-12-28 20:29
Hello,
I have the same error
logs
![iAMjpav](https://user-images.githubusercontent.com/59397088/147604704-caa82bf0-9801-48bf-93f5-af460b904578.png)

**Comment by dopplershift** [comment] 2022-02-03 18:35
Seeing the same issue on [this repo](https://github.com/Unidata/MetPy). [Here's](https://github.com/Unidata/MetPy/runs/5056365907?check_suite_focus=true#step:13:1) a representative action run:
```
Post job cleanup.
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/MetPy/MetPy --files-from manifest.txt
/usr/bin/tar: ../../../work/_temp/bdee9e41-e8-4f2a-9912-6eb32de36aa/cache.tzst: file changed as we read it
Warning: Tar failed with error: The process '/usr/bin/tar' failed with exit code 1
Post job cleanup.
Cache hit occurred on the primary key setup-python-Linux-pip-9225292fdf311547e1fda261cbc2734e26bc2c516bdcf7d87f5c7af6de21fb8c, not saving cache.
```

**Comment by sammcj** [comment] 2022-05-30 05:39
Can confirm this is still an issue.

zstd is installed but:

```
/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/ec2-user/actions-runner/_work/my-repo/my-repo --files-from manifest.txt
tar (child): zstd -T0: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
```

**Comment by kotewar** [comment] 2022-05-30 09:48
@sammcj - your error seems to be a different one as the file/directory doesn't exist at the first place. Can you please check if the path(s) that you have provided in your configuration exist?

**Comment by kotewar** [comment] 2022-05-30 10:22
@MatthieuLeboeuf, @dopplershift @cyberpwnn  can you please share the `path` used for caching and approximate cache size in your repos where you came across this issue?

**Comment by kotewar** [comment] 2022-06-06 09:52
@dopplershift thanks for sharing the path. The logs you have shared are not available anymore. Requesting you to please share the run if you come across the situation again.

**Comment by dopplershift** [comment] 2022-06-06 19:03
It's been failing pretty consistently for the last 6 months, so I appreciate you taking a look. Here's the [most recent failure](https://github.com/Unidata/MetPy/runs/6752838344?check_suite_focus=true#step:13:5) from last night.

**Comment by kotewar** [comment] 2022-06-07 03:04
@dopplershift I am planning to release a fix (v3.0.4) today, I'll let you know once its available for testing.

**Comment by kotewar** [comment] 2022-06-10 05:26
I am hoping the problem is resolved for all now. Hence closing the issue.

**Closed by kotewar** 2022-06-10 05:26 UTC
Labels: bug

**Comment by dopplershift** [comment] 2022-06-12 01:58
I can confirm that moving to `@v3` fixes this particular issue for me.

I'm having a different problem now where it can't find the cache (after successfully saving), but the fact that you can't list what caches are present it making debugging more than a little difficult. I'll open an issue if I can ever get my hands around it.
