### ISSUE TITLE
Can we have cache size more than 400MB?

### ISSUE THREAD

**Issue by deltaguita** [actions/cache#138] opened 2019-12-25 06:34 UTC
Hi
My team run android CI/CD with Action,  the gradle cache size is always more than 400MB( just so heavy) so we can't cache that, downloading dependencies every time is very time consuming...

Can we have cache size more than 400MB?

**Comment by LouisCAD** [comment] 2019-12-26 09:12
Duplicate of #6

**Comment by joshmgross** [comment] 2019-12-26 15:53
Closing as duplicate of #6 

The size limited will be increased soon

**Closed by joshmgross** 2019-12-26 15:53 UTC
