### ISSUE TITLE
`getCacheEntry failed: Cache service responded with 503`

### ISSUE THREAD

**Issue by LuudJanssen** [actions/cache#820] opened 2022-06-13 08:04 UTC
This is a duplicate or re-open of #698, but I wanted to draw your attention to the fact that this is happening again. Given the amount of comments in the last half hour, I think this problem is affecting a lot of users.

Feel free to close this issue when it's already on your radar.

**Comment by ChristianGrete0770** [comment] 2022-06-13 08:12
Same here.

**Comment by link-jc** [comment] 2022-06-13 08:15
Same here.

**Comment by Beyarz** [comment] 2022-06-13 08:16
Same here.

**Comment by aronhoyer** [comment] 2022-06-13 09:20
relating to this, should this maybe fail the action instead of just logging a warning?

**Comment by nicolas-sicard-adeo** [comment] 2022-06-13 09:36
question: should this be an error instead of a warning as it will impact the rest a workflow?

**Comment by danijelgrabez** [comment] 2022-06-13 10:06
+1

**Comment by Kurt-von-Laven** [comment] 2022-06-13 10:38
[Here](https://github.com/ScribeMD/pre-commit-hooks/runs/6859571223?check_suite_focus=true) is a reproduction with debug logs enabled for your convenience.

**Comment by ReshaSD** [comment] 2022-06-13 10:42
> Should this be an error instead of a warning as it will impact the rest of a workflow?

This shouldn't be an error. Is my case I can make workaround and check 
```
        if: steps.RESTORE-STUFF.outputs.cache-hit != 'true'
        run: DO_SMTH
```
But if this would be an error - whole deployment will fail.

**Comment by anunay-sanuk** [comment] 2022-06-13 10:59
same. +1

**Comment by ujjwal-deswal** [comment] 2022-06-13 11:00
same +1

**Comment by petervmeijgaard** [comment] 2022-06-13 11:00
> same. +1

As @LuudJanssen stated:
> Let's try to keep the comment thread clean and avoid the "Same here" comments. A thumbs up +1 is enough to let the maintainers know it's also affecting you.

**Comment by mohammedazfar-sanuk** [comment] 2022-06-13 11:01
+1

**Comment by foxylion** [comment] 2022-06-13 11:07
I also would highly suggest that this action should be more resilient regarding service outages in the backing caching infrastructure. The builds would most probably just work if the cache action would do "nothing" when the caching backend can't be reached.

The workaround provided by @ReshaSD might be okay if you've a single workflow. But we have hundreds of workflow and it is not suitable to modify every single workflow.

**Comment by douglascbarbosa** [comment] 2022-06-13 11:15
> Same here

**Comment by RWilliams-MicronAgritech** [comment] 2022-06-13 11:21
Hey guys, for a temporary fix. Find cache: 'npm' and simply comment this line out and bypass caching. 

Hope this helps 👍

**Comment by mohammedazfar-sanuk** [comment] 2022-06-13 11:22
> Hey guys, for a temporary fix. Find cache: 'npm' and simply comment this line out and bypass caching.
> 
> Hope this helps 👍

for maven any suggestions ?

**Comment by maurobringolf** [comment] 2022-06-13 11:24
If anyone has a workaround using https://github.com/ocaml/setup-ocaml, I'm happy to hear it :v:

**Comment by grasshoppergn** [comment] 2022-06-13 11:26
try adding `continue-on-error: true` to the setup step

**Comment by michaelniemand** [comment] 2022-06-13 11:30
> try adding `continue-on-error: true` to the setup step

for a yarn build this will actually go to the next step which then fails because the dependencies aren't there

**Comment by madhan-mettle** [comment] 2022-06-13 11:39
Seems like the issue is gone. Atleast for me

**Comment by RSickenberg** [comment] 2022-06-13 11:40
https://www.githubstatus.com/ has now the outrage marked.

**Comment by tiwarishub** [comment] 2022-06-13 11:54
👋  team, we are seeing issues with Github Action cache service. We are looking into it. ``actions/cache`` should not fail as we throw only warning if there is some issue in cache service  There must be other ``actions/setup-*``  https://github.com/actions/setup-java/issues/343 and https://github.com/actions/setup-node/issues/516 which are using caching service and they might be throwing error instead of warning And for those scenarios we should not use cache param till we get issue resolved. Sorry for inconvenience 🙇

**Comment by sugarandmagic** [comment] 2022-06-13 12:01
> [githubstatus.com](https://www.githubstatus.com/) has now the outrage marked.

little freudian slip 😂

**Comment by jas88** [comment] 2022-06-13 12:27
In general I would say a cache error like this should be treated as a cache miss rather than an error condition - any workflow where caching is actually essential (ie the failure really should be an error) is surely an exception, if one exists at all?

**Comment by guergana** [comment] 2022-06-13 13:12
same problem.

**Comment by Indronil** [comment] 2022-06-13 13:20
Hi,

I am having the same issue in my CI system just started occurring today for the first time. It was working fine without any issue until Friday.

Run actions/setup-node@v2
Found in cache @ /opt/hostedtoolcache/node/14.19.3/x64
/usr/local/bin/yarn --version
1.22.[18](https://github.com/viacomcbs/vcap-platform-applications/runs/6860584429?check_suite_focus=true#step:3:19)
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Error: getCacheEntry failed: Cache service responded with 503

Is it an issue from github side and will it be solved soon? We can live without cache until then if that is the case?

**Comment by anuragc617** [comment] 2022-06-13 13:36
Hi all, the issue has been mitigated. Please confirm the same. Thanks for your patience 🙇

**Comment by sakulstra** [comment] 2022-06-13 13:45
Partially, some ci runs seem to work, some still error with `Error: getCacheEntry failed: Cache service responded with 503`

**Comment by genisd** [comment] 2022-06-13 13:59
It seems to be recovering here. I see successful runs since about ~10 minutes ago

**Comment by sakulstra** [comment] 2022-06-13 14:11
@tiwarishub  seems to work again.

**Comment by matthew-gill** [comment] 2022-06-13 14:41
[Here's the official incident from GH](https://www.githubstatus.com/incidents/6r4sms3hcj3x)

It's resolved. Confirmed from my side and commentary above seems to confirm it.

Suggest we go ahead and close this issue out.

**Closed** 2022-06-13 14:42 UTC
