### ISSUE TITLE
Post action failed with Error: No such container

### ISSUE THREAD

**Issue by samhamilton** [actions/cache#78] opened 2019-11-09 10:29 UTC
When trying to save a new cache I get an error, but seeing as there was no cache hit at the start of the job it is a bit weird.

```
Post job cleanup.
/usr/bin/docker exec  b41de5d1c382827f57c505ea59d0741bb205fddc841d2aae747e845b338f36ea sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
Error: No such container: b41de5d1c382827f57c505ea59d0741bb205fddc841d2aae747e845b338f36ea
##[error]Node run failed with exit code 1
```

I created an open version here https://github.com/samhamilton/phoenix_hello/commit/eb71e941b763caa4df121f28b7085c14fb17f585/checks?check_suite_id=303196383

Thanks
Sam

**Comment by nhooyr** [comment] 2019-11-11 02:46
Same issue here.

**Comment by nhooyr** [comment] 2019-11-11 02:46
https://github.com/nhooyr/site/pull/20/checks?check_run_id=296887667#step:14:1

**Comment by gmile** [comment] 2019-11-11 12:17
Looks like a duplicate of https://github.com/actions/cache/issues/12

**Comment by samhamilton** [comment] 2019-11-11 13:18
@gmile wasn't totally sure as they had a cache to start with and for me it breaks both with and without cache

**Comment by joshmgross** [comment] 2019-11-12 19:10
Duplicate of #12 

We've rolled out an updated hosted runner that fixes for post actions in container jobs.

**Closed by joshmgross** 2019-11-12 19:10 UTC
