### ISSUE TITLE
v2 never works, always says "Cache not found"

### ISSUE THREAD

**Issue by jcayzac** [actions/cache#369] opened 2020-07-14 03:47 UTC
In a very simple pnpm project, `actions/cache` always gives me `Cache not found`. The step is configured as follow:

```yaml
- name: 'Cache node modules'
  uses: actions/cache@v2
  with:
    path: '**/node_modules'
    key: ${{ runner.os }}-node-modules
```

…whereas the log for the _post_ action says the cache is saved successfully:

```txt
Post job cleanup.
/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/foo/foo --files-from manifest.txt
Cache saved successfully
Post job cleanup.
/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/foo/foo --files-from manifest.txt
Cache saved successfully
```

**Comment by jcayzac** [comment] 2020-07-14 03:50
More info: the workflow executes on pull requests. I have two branches, `master` (target of the PRs) and `hotfix/github` (source branch, on the same repo). Nothing very fancy.

**Comment by jcayzac** [comment] 2020-07-14 04:12
So far from my test it seems that the cache is only ever found for subsequent builds of the _same_ pull request, which makes it pretty much completely useless.

**Comment by dhadka** [comment] 2020-07-14 13:48
@jcayzac Yes, that is by design (see [Restrictions for accessing a cache](https://docs.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache)).  Once one of the PRs is merged, the cache should then be visible to other PRs.  There are [discussions](https://github.com/actions/cache/issues/79) to change this behavior and allow sharing of caches between PRs in the same repo (not forks), but nothing is in the works at the moment.

**Comment by aiqiaoy** [comment] 2020-07-16 20:08
Closing as by design

**Closed by aiqiaoy** 2020-07-16 20:08 UTC
