### ISSUE TITLE
Excluded sub directory not working

### ISSUE THREAD

**Issue by mustaphazorgati** [actions/cache#494] opened 2020-12-25 05:17 UTC
Hey there!
The README.md provides an example where an excluded sub-path is provided. Unfortunately that sub-path still ends up in the cache.
Here is a modified example using the local maven repository.
```
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: |
      ~/.m2
      !~/.m2/pro/taskana
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
```

Reading out on the next (cached) build the files in `~/.m2/pro/taskana` are contained in the cache. The following adjustment didn't work either: 
```
- name: Cache multiple paths
  uses: actions/cache@v2
  with:
    path: |
      ~/.m2
      !~/.m2/pro/taskana/**
    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
```

Is this a bug or am I having the wrong expectations? Our current workaround is to delete that subfolder in a dedicated step. It works, but is kinda annoying.

**Comment by mustaphazorgati** [comment] 2021-02-08 09:13
@dhadka I've seen you answering a lof of issues recently. Sorry for asking you directly, but can you have a look at this?

**Comment by dhadka** [comment] 2021-02-08 15:30
@mustaphazorgati Thanks for reporting this (and sorry I didn't see this earlier).  I was able to [reproduce this issue](https://github.com/dhadka/cache-test-exclusion/runs/1855643206?check_suite_focus=true).  I filed a [bug over in the actions/toolkit repo](https://github.com/actions/toolkit/issues/713) that hosts the underlying logic for search patterns.

**Comment by mustaphazorgati** [comment] 2021-02-08 22:51
Thank you @dhadka for your quick response! 
Just an FYI for other readers: The provided reproduction of the issue is found [here](https://github.com/dhadka/cache-test-exclusion/runs/1855553990?check_suite_focus=true). 
@dhadka link shows a workflow where the `Post cache test` step is not executed ;)

**Comment by Adnn** [comment] 2021-09-20 18:10
Any update on this issue? (This is making the cache difficult to use in complex workflows)

**Comment by robinp** [comment] 2022-02-05 20:24
FYI guys I added some code pointers to the underlying https://github.com/actions/toolkit/issues/713#issuecomment-1030692990 - for me it seems passing an extra option to avoid matching directiories in the globber would solve this.

**Comment by Phantsure** [comment] 2022-04-08 10:11
This issue still exists?

**Comment by aparna-ravindra** [comment] 2022-10-07 09:25
While the issue still exists, the readme file has changed since then and this example is not part of it anymore. Closing this issue in favour of the issue created in the toolkit repo [here](https://github.com/actions/toolkit/issues/713) to fix the problem.

**Closed by aparna-ravindra** 2022-10-07 09:25 UTC
Labels: documentation

**Comment by Jimimaku** [comment] 2022-11-21 17:22
> Hey there! The README.md provides an example where an excluded sub-path is provided. Unfortunately that sub-path still ends up in the cache. Here is a modified example using the local maven repository.
> 
> ```
> - name: Cache multiple paths
>   uses: actions/cache@v2
>   with:
>     path: |
>       ~/.m2
>       !~/.m2/pro/taskana
>     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
> ```
> 
> Reading out on the next (cached) build the files in `~/.m2/pro/taskana` are contained in the cache. The following adjustment didn't work either:
> 
> ```
> - name: Cache multiple paths
>   uses: actions/cache@v2
>   with:
>     path: |
>       ~/.m2
>       !~/.m2/pro/taskana/**
>     key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
> ```
> 
> Is this a bug or am I having the wrong expectations? Our current workaround is to delete that subfolder in a dedicated step. It works, but is kinda annoying.
