### ISSUE TITLE
Identical cache key hits on ubuntu/mac, but misses on Windows

### ISSUE THREAD

**Issue by mcg1969** [actions/cache#362] opened 2020-07-06 04:23 UTC
In [this run](https://github.com/conda/conda-pack/actions/runs/158855067) I have created a cached asset in [the `package` step](https://github.com/conda/conda-pack/runs/840080186?check_suite_focus=true) with the key `package-5fc9dd41a6ade85100c424bab5b08d65d79922d1`:
```
Run actions/cache@v2
  with:
    path: build
    key: package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
Cache not found for input keys: package-5fc9dd41a6ade85100c424bab5b08d65d79922d1

Post job cleanup.
/bin/tar --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/conda-pack/conda-pack --files-from manifest.txt
Cache saved successfully
```
All of the MacOS and Linux variants in my `tests` job successfuly find the cache; e.g. [this one](https://github.com/conda/conda-pack/runs/840082631?check_suite_focus=true):
```
Run actions/cache@v2
  with:
    path: build
    key: package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
Cache Size: ~0 MB (41307 B)
/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/51c1d57a-7530-487c-95ad-4a7fcb4d58cb/cache.tzst -P -C /home/runner/work/conda-pack/conda-pack
Cache restored from key: package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
```
None of the `Windows` variants do; e.g., [this one](https://github.com/conda/conda-pack/runs/840082674?check_suite_focus=true):
```
Run actions/cache@v2
  with:
    path: build
    key: package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
Cache not found for input keys: package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
```
Remember, these are all parallel runs of exactly the same build step. Will try to post some debugging information when I can figure out how to do it.

**Comment by mcg1969** [comment] 2020-07-06 04:43
Updated [this run](https://github.com/conda/conda-pack/runs/840128054) with debugguing information.

Here's the log for a failed hit:
```
##[debug]Register post job cleanup for action: actions/cache@v2
##[debug]Loading inputs
##[debug]Evaluating: format('package-{0}', github.sha)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'package-{0}'
##[debug]..Evaluating Index:
##[debug]....Evaluating github:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'sha'
##[debug]..=> '5fc9dd41a6ade85100c424bab5b08d65d79922d1'
##[debug]=> 'package-5fc9dd41a6ade85100c424bab5b08d65d79922d1'
##[debug]Result: 'package-5fc9dd41a6ade85100c424bab5b08d65d79922d1'
##[debug]Loading env
Run actions/cache@v2
::save-state name=CACHE_KEY::package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
##[debug]Save intra-action state CACHE_KEY = package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
##[debug]Resolved Keys:
##[debug]["package-5fc9dd41a6ade85100c424bab5b08d65d79922d1"]
##[debug]Checking tar --version
##[debug]bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.5.f-ipp
##[debug]Resource Url: https://artifactcache.actions.githubusercontent.com/SyPiuWRZfZhgosQnlbkVj8WEdMgSzKZ74mqmotYBPmK4Oixovs/_apis/artifactcache/cache?keys=package-5fc9dd41a6ade85100c424bab5b08d65d79922d1&version=f641f16661dc3609f08841cc60405d8625b8976a3c51195cbfa1dcee689de520
Cache not found for input keys: package-5fc9dd41a6ade85100c424bab5b08d65d79922d1
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Retrieve the build artifact cache
```
Here are the successful Urls from a Linux and Mac cache hit, respectively:
```
https://artifactcache.actions.githubusercontent.com/SyPiuWRZfZhgosQnlbkVj8WEdMgSzKZ74mqmotYBPmK4Oixovs/_apis/artifactcache/cache?keys=package-5fc9dd41a6ade85100c424bab5b08d65d79922d1&version=d67e0235b9192999f3e9ffe31d1864c1878d3fb9c5da52d2bfc8fc07af8f0e90
https://artifactcache.actions.githubusercontent.com/SyPiuWRZfZhgosQnlbkVj8WEdMgSzKZ74mqmotYBPmK4Oixovs/_apis/artifactcache/cache?keys=package-5fc9dd41a6ade85100c424bab5b08d65d79922d1&version=d67e0235b9192999f3e9ffe31d1864c1878d3fb9c5da52d2bfc8fc07af8f0e90
```
As you can see, the `keys` entry is the same, but the `version` entry is not.

**Comment by mcg1969** [comment] 2020-07-06 04:49
It looks like the `version` key is a function of the compression program, which differs between Windows and Mac.

**Comment by mcg1969** [comment] 2020-07-06 04:52
Looking at the discussion in https://github.com/actions/cache/issues/301 and also in the README.md about the use of `zstd` on Linux and macOS, it looks like this is a semi-known issue, but it sure needs to be documented. I don't like hearing sob stories as a developer myself but I've literally spent hours wrestling `actions/cache` into shape here only to be stopped on the 5 yard line :-( I guess I'll have to use artifact uploads instead.

**Comment by milosmns** [comment] 2020-12-20 14:43
I'm experiencing a similar issue (also working fine on linux/mac and failing to store anything on windows)... https://github.com/milosmns/tema/actions/runs/434017347

Looks like some folder permission issue... On my side it's a Kotlin/Native showcase project

**Comment by rikardn** [comment] 2021-02-19 07:07
I have the same problem in two different workflows. First caching on `ubuntu-latest` in one job, then using the cache in ubuntu, macos and windows in other jobs. In ubuntu and macos it works fine, but in Windows I get `cache not found`.

See my failed runs here: https://github.com/UUPharmacometrics/PsN/runs/1928546379?check_suite_focus=true and here https://github.com/pharmpy/pharmpy/runs/1928367509?check_suite_focus=true

Let me know if I can assist in resolving this in any way.

**Comment by milosmns** [comment] 2022-03-10 09:00
Is it fixed though?

**Comment by pdotl** [comment] 2022-09-07 14:14
👋  @milosmns @rikardn @mcg1969 @mzabaluev this behaviour is due to difference in compression algorithms used. Linux and macos use `zstd` but Windows does not due to issues. We have this documented and also a workaround. Please refer to the [documentation](https://github.com/actions/cache/blob/main/workarounds.md#improving-cache-restore-performance-on-windowsusing-cross-os-caching) to if you want to use cross-os caching with Windows. Closing this issue as it is a duplicate of https://github.com/actions/cache/issues/888.

**Closed by pdotl** 2022-09-07 14:14 UTC
Labels: bug, area:compression

**Comment by milosmns** [comment] 2022-09-07 15:36
Hey @pdotl, thanks for getting back to this 🙏 

Since you just mentioned that there's a documented workaround for this problem, is it possible to make that workaround the default behavior? I ask about this because (at least for me) having cross-os support is the default thing I want when building on multiple platforms.

And if not, it's also ok, but it would be nice to get some reasoning behind the decision if possible 😅 

Thanks!

**Comment by pdotl** [comment] 2022-09-07 19:01
@milosmns there were multiple issues with `zstd` on windows due to which it had to be disabled, causing different cache version on windows. We are looking into restoring the cross-os behaviour as default. Meanwhile, hopefully the workaround helps.

**Comment by milosmns** [comment] 2022-09-07 19:16
Awesome, good to know. Cheers.
