### ISSUE TITLE
Possible to use specific OS version for cache keys?

### ISSUE THREAD

**Issue by albaer** [actions/cache#543] opened 2021-02-24 16:40 UTC
Hi! We're loving github actions so far. This is a small request related to variables available for cache keys.

We use {{ runner.os }} in our cache keys, like most of the docs here and examples I’ve seen around the internet. When ubuntu-latest was updated from 18 to 20, the build failed and I was surprised to see that it was because the cache wasn’t busted. Looking into it, {{ runner.os }} returns “Linux” (or “macOS” or similar), so it didn’t change even though our OS did. I would prefer to include the actual os version (e.g. ubuntu-20-04 or similar) in my cache keys so that the cache is busted when we change the os version. After looking around a bit, I don’t see an easy way to do this. I [posted this in the community](https://github.community/t/possible-to-get-specific-os-version-for-cache-keys/162282), but so far no one seems to have a workaround.

What do you all think about having `runner.os_version` variable or something similar available?

**Comment by matt335672** [comment] 2021-03-04 12:27
Hi @albaer 

For info, I've proposed a [workaround](neutrinolabs/xrdp#1821)  to the xrdp project where we cache a version of cppcheck. We got bitten by this too.

Have a look at the first commit neutrinolabs/xrdp@984e8d12c062e2517487198edbe040e3cdbb928b in the PR.

We'd like a better solution too! Hope this is useful in the meantime however.

**Comment by pzhlkj6612** [comment] 2021-03-05 05:51
[Off topic]

Hi @matt335672 . The first link in your post points to an invalid page, and you may need to fix it.

```diff
- [workaround](neutrinolabs/xrdp#1821)
+ [workaround](https://github.com/neutrinolabs/xrdp/pull/1821)
```

Or,

```diff
- [workaround](neutrinolabs/xrdp#1821)
+ workaround (neutrinolabs/xrdp#1821)
```

That is, if you want to use a GitHub generated link, you should not put it in a Markdown link.

**Comment by albaer** [comment] 2021-03-15 15:46
Thanks for the workaround tip, @matt335672!

**Comment by ffried** [comment] 2021-07-30 09:31
This just hit me as well. Since the workaround only covers Linux and we need this on macOS as well, I've written a small action [os-version-action](https://github.com/sersoft-gmbh/os-version-action) that reads the version.

I still consider this somewhat of a workaround and am totally in favor of having this e.g. in the `runner` context.

**Comment by Kurt-von-Laven** [comment] 2021-11-19 07:42
This isn't glamorous, but you can use `${{ matrix.os }}` as the value of `runs-on`, and include it in the cache key provided that you define `strategy.matrix.os` to a suitable array of runners (e.g., `[ubuntu-20.04]`) as documented by https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#example-running-with-multiple-operating-systems.

**Comment by Phantsure** [comment] 2022-05-20 10:55
Here is a workaround for now which works irrespective of OS. This is the similar way used to get cache path on windows.
<img width="514" alt="Screenshot 2022-05-20 at 4 20 12 PM" src="https://user-images.githubusercontent.com/25999504/169512950-141a4a44-ecff-4b6c-9b52-8fd85e6dbb26.png">
Note: It may help, if you think your build might fail due to OS upgrades, to put `runs-os: ubuntu-18.04` or similar to keep them on same OS and upgrade as per your needs.
For the `runner` context variable, we don't have any plans for that in near future, so closing this for now.

**Closed by Phantsure** 2022-05-20 10:55 UTC

**Comment by Kurt-von-Laven** [comment] 2022-05-20 23:51
Since there are a lot of folks on this thread, please note that the first step simply creates a file containing random contents and is for illustration purposes only. You would only need to copy the second step (reproduced below for your convenience) and use it in your cache step as illustrated in the third step (by referencing `${{ steps.os.outputs.image }}`). On a side note, the inner use of `echo` in the second step is unnecessary, and the correct key is `runs-on` rather than `runs-os`.

```yaml
- name: Get operating system name and version.
  id: os
  run: echo "::set-output name=image::$ImageOS"
```
