### ISSUE TITLE
Cache decompression slow on Windows

### ISSUE THREAD

**Issue by craffael** [actions/cache#442] opened 2020-10-21 19:06 UTC
For me decompression of a cache on Windows is much slower than on linux. A [360Mb cache](https://github.com/craffael/lehrfempp/runs/1288591548) takes
- only 10sec to download
- but 5 minutes to decompress!

The cache consists of many small files (e.g. the [boost library](https://www.boost.org/)) which probably affects performance negatively.

It seems that [appveyor switched to 7zip](https://www.appveyor.com/docs/build-cache/#cache-speed-vs-size-beta) to compress/decompress the cache exactly for performance reasons. Maybe this would also be on option for github actions that run on windows?

Also note that there was already a similar issue (#336) but it was fixed by improving network performance. Here the bottleneck is not the network but the decompression itself...

**Comment by Leseratte10** [comment] 2020-11-10 11:00
I noticed that issue as well. I thought I could use the cache so I don't have to download the needed compilers and libraries for every run, but loading and extracting them from the cache takes way longer than just redownloading them. That makes the cache pretty useless for my use case.

**Comment by quanglam2807** [comment] 2020-12-26 17:58
I also have this problem. I run the same job on Linux, macOS & Windows. And while macOS & Linux take less than 1 minutes, Windows takes almost 4 minutes.

**Comment by arvinxx** [comment] 2021-02-06 06:34
Yes, I meet this problem too, the Windows cost almost 5mins every cache. It really a time waste !!!

**Comment by airglow923** [comment] 2021-02-10 17:14
Experienced the same issue on Windows. Here's the config I used:

```yaml
- name: Get yarn cache directory
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

- name: Query yarn cache
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
```

On `ubuntu-lastest`:

![image](https://user-images.githubusercontent.com/37762634/107545536-5fee7a00-6c06-11eb-9d5c-153fd3badbd8.png)

On `windows-latest`:

![image](https://user-images.githubusercontent.com/37762634/107545596-71378680-6c06-11eb-83b8-68c631ac539a.png)

As you can see, that margin is extreme.

**Comment by aminya** [comment] 2021-06-01 12:28
I have experienced the same issue. Setting up a cache with a size of 800 MB takes 20 seconds on Ubuntu while the smaller 600 MB cache takes about 1 min. 


They use different commands which can be the reason for the slow decompression. I wonder if actions should use 7z on Windows instead of tar.

```
/usr/bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/123/cache.tzst -P -C /home/runner/work/proj/proj
```

```
C:\Windows\System32\tar.exe -z -xf D:/a/_temp/123/cache.tgz -P -C D:/a/proj/proj
```

**Comment by aminya** [comment] 2021-06-02 03:33
They have disabled zstd compression on Windows, and that is why Windows caching is so slow:

https://github.com/actions/toolkit/blob/439eaced077b820cbf01183f71a220813514a95b/packages/cache/src/internal/cacheUtils.ts#L88-L91

**Comment by coreysharris** [comment] 2021-06-14 19:49
Seeing the same thing. Here using `actions/cache@v2` on `windows-latest` (911 MB in 232 secs):
```
Mon, 14 Jun 2021 19:09:23 GMT Cache Size: ~911 MB (954772818 B)
Mon, 14 Jun 2021 19:09:23 GMT C:\Windows\System32\tar.exe -z -xf D:/a/_temp/43c0bd85-e872-49a2-8d1d-79821cfaf45d/cache.tgz -P -C D:/a/...
Mon, 14 Jun 2021 19:13:15 GMT Cache restored successfully
```

 And here on `ubuntu-18.04` (934 MB in 19 secs):
```
Mon, 14 Jun 2021 19:08:58 GMT Cache Size: ~934 MB (979124632 B)
Mon, 14 Jun 2021 19:08:58 GMT /bin/tar --use-compress-program zstd -d -xf /home/runner/work/_temp/cb044a1c-0a29-4b6c-a0d5-34ac07f43d8c/cache.tzst -P -C /home/runner/work/...
Mon, 14 Jun 2021 19:09:17 GMT Cache restored successfully
```

**Comment by shichen85** [comment] 2022-01-17 17:24
Also having a very slow cache restore operation for unzipped gradle-7.0.2-all.zip contents at the path `C:\Users\runneradmin\.gradle\wrapper\dists\gradle-7.0.2-all` on a Windows runner. Downloading the zip file and decompressing it takes under 2 minutes, whereas using cache restore would take up to 3m43s.

**Comment by Safihre** [comment] 2022-02-08 14:55
I am seeing the same thing, it's just too slow! 
Can the team not do something about this? Just pinging some recently active devs @vsvipul, maybe you can help?

**Comment by Safihre** [comment] 2022-02-09 11:11
Just as an update: I just switched to `runs-on: windows-2022` and suddenly the decompression times are 4x faster. Still slower than Linux/macOS, but much improved. Maybe other see the same?
But: still too slow!

**Comment by mattjohnsonpint** [comment] 2022-05-09 17:46
@Safihre - Still to slow for me, even on windows-2022.  See https://github.com/actions/cache/issues/752#issuecomment-1119931553

**Comment by Safihre** [comment] 2022-05-09 18:12
Yeah, I also saw it in my runs. 
But based on the lack of any responses here, they (Github) don't seem to care at all.

**Comment by pdotl** [comment] 2022-08-22 14:15
Hi @shichen85 @coreysharris @Safihr. As @aminya observed, `zstd` is disabled on Windows due issues with bsd tar. We are working on a longer term solution. You could meanwhile use the workaround suggested [here](https://github.com/actions/cache/issues/591) to improve performance. This would enable zstd while using GNU tar.

TLDR; Add the following step to your workflow **before** the cache step. That's it.

```
- if: ${{ runner.os == 'Windows' }}
      name: Use GNU tar
      shell: cmd
      run: |
        echo "Adding GNU tar to PATH"
        echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
```
Hope this helps.

**Comment by Safihre** [comment] 2022-08-22 18:41
For my project this makes it even slower.. Taking 1:20 min to unpack 35MB 😑
Anyone else having better results?

**Comment by pdotl** [comment] 2022-08-22 19:05
@Safihre could you share your workflow file or the sample run or logs if possible?

**Comment by pdotl** [comment] 2022-08-22 19:58
@Safihre I'm not sure what the issue is. I tried running a similar albeit simpler workflow to yours using the `syphar/restore-virtualenv@v1.2` action but still found windows to be reasonably fast for ~24 mb cache. https://github.com/pdotl/sample-cache-demo/actions/runs/2906664955

**Comment by aminya** [comment] 2022-08-22 20:13
The zstd compression is still disabled on Windows. How does this workaround help?
https://github.com/actions/toolkit/blob/bc4be505973a6a7344bfd71e1b32f77e1755310c/packages/cache/src/internal/cacheUtils.ts#L93

**Comment by pdotl** [comment] 2022-11-16 08:43
We are tracking this issue in #984. Please check the current proposal there and provide comments/feedback if any. Closing this as duplicate.

**Closed by pdotl** 2022-11-16 08:43 UTC
Labels: bug, duplicate, area:compression
