### ISSUE TITLE
Cache not found for input keys

### ISSUE THREAD

**Issue by dschinkel** [actions/cache#493] opened 2020-12-23 08:42 UTC
Not sure what I'm missing here:

```js
jobs:
  tests:
    name: Run all tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)yarn cache dir
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
```

![Screen Shot 2020-12-23 at 2 42 01 AM](https://user-images.githubusercontent.com/338798/102977399-8c203100-44c8-11eb-9f13-d927df015b2b.jpg)

**Comment by jsakas** [comment] 2021-02-24 05:44
Same. Whats really weird is that I use the same config for multiple projects and in some it works, some it doesn't. 

```
    - name: Restore Cache
      id: cache-deps
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install Dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: |
        yarn install
```

```
Cache not found for input keys: Linux-yarn-1b6a7f6e83927fcd83e5a89ce8029cb02cc9d0a410abfdbfb7b48f78565a36fe, Linux-yarn-
```

**Comment by rhyek** [comment] 2021-02-24 16:45
I just hit this issue during a pull request workflow. I am caching two things for my pnpm-based project: the pnpm store (sort of like npm cache) and node_modules. node_modules is only meant to be cached for the current GITHUB_SHA so that it doesn't transcend commits, but is used in all jobs within the workflow. However the pnpm store is supposed to be used between PRs and i consistently get the cache not found for input keys error:

```yaml
steps:
  - name: Cache pnpm store
    uses: actions/cache@v2
    with:
      path: ~/.pnpm-store
      key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      restore-keys: |
        ${{ runner.os }}-pnpm-store-
  - name: Cache node_modules
    uses: actions/cache@v2
    with:
      path: '**/node_modules'
      key: ${{ runner.os }}-tests-node-modules-${{ github.sha }}
```
I thought that maybe the node_modules cache was getting so big it was pushing out the pnpm store one, but they are both around 50MB when they get saved according to the logs, so that's not it.

Output:
```
Run actions/cache@v2
  with:
    path: ~/.pnpm-store
    key: Linux-pnpm-store-daa48f5a4ec773032ddae1d149beb21f15bef5f424c45df10a2669205d4cae30
    restore-keys: Linux-pnpm-store-
  
  env:
    DOCKER_BUILDKIT: 1
Cache not found for input keys: Linux-pnpm-store-daa48f5a4ec773032ddae1d149beb21f15bef5f424c45df10a2669205d4cae30, Linux-pnpm-store-
```

*However*, if i disable the node_modules cache i can see that the pnpm store one is found every time. This is confusing.

**Comment by linonetwo** [comment] 2021-06-02 14:39
Mine is even weird:

```
Run actions/cache@v2
  with:
    path: ~/.npm
    key: macOS-node-82c40bafd2760bf2421dccb7f83e288b3baf58b5d6fcc263ad4d07c6d52e9f5a
    restore-keys: macOS-node-82c40bafd2760bf2421dccb7f83e288b3baf58b5d6fcc263ad4d07c6d52e9f5a
  macOS-node-
  
Cache not found for input keys: macOS-node-82c40bafd2760bf2421dccb7f83e288b3baf58b5d6fcc263ad4d07c6d52e9f5a, macOS-node-82c40bafd2760bf2421dccb7f83e288b3baf58b5d6fcc263ad4d07c6d52e9f5a, macOS-node-
```

**Comment by aminya** [comment] 2021-06-04 06:15
> I just hit this issue during a pull request workflow. I am caching two things for my pnpm-based project: the pnpm store (sort of like npm cache) and node_modules. node_modules is only meant to be cached for the current GITHUB_SHA so that it doesn't transcend commits, but is used in all jobs within the workflow. However the pnpm store is supposed to be used between PRs and i consistently get the cache not found for input keys error:
> 
> ```yaml
> steps:
>   - name: Cache pnpm store
>     uses: actions/cache@v2
>     with:
>       path: ~/.pnpm-store
>       key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
>       restore-keys: |
>         ${{ runner.os }}-pnpm-store-
>   - name: Cache node_modules
>     uses: actions/cache@v2
>     with:
>       path: '**/node_modules'
>       key: ${{ runner.os }}-tests-node-modules-${{ github.sha }}
> ```
> 
> I thought that maybe the node_modules cache was getting so big it was pushing out the pnpm store one, but they are both around 50MB when they get saved according to the logs, so that's not it.
> 

For pnpm, do not cache node_modules. Only cache the pnpm-store and also remove `pnpm-lock.yaml` key. Node_modules is just a bunch of symlinks, and the time it takes to recreate them is more than if pnpm itself does it directly.
See #585

**Comment by linonetwo** [comment] 2022-05-05 08:38
I think the problem is still there

**Comment by vsvipul** [comment] 2022-05-05 09:19
@linonetwo Hi Will you be able to share the workflow here and if the repo is public, also the workflow run and/or logs? I'll take a look.

**Comment by linonetwo** [comment] 2022-05-05 09:51
Oh, most of issuer above is using v2, let me try v3! One of my friends' new repo that is using v3 is working nicely.

**Comment by vsvipul** [comment] 2022-05-07 12:07
@linonetwo any update?

**Comment by linonetwo** [comment] 2022-05-07 13:51
I figure out why...My friends' working example doesn't update "version" in the packagejson, so `package-lock.json` won't update too.

But in my project, I update version and run npm i to update version in the package-lock.json, so this invalidate the `key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}`

So this is all my bad, I think this can be closed?

**Comment by vsvipul** [comment] 2022-05-07 13:57
Yes, package-lock file only changes after doing `npm i`. So, this should be the reason. Closing now. Thank you.

**Closed by vsvipul** 2022-05-07 13:57 UTC
