### ISSUE TITLE
Primary cache should be re-evaluated when deciding whether to update the cache in post-job phase

### ISSUE THREAD

**Issue by fransf-wtax** [actions/cache#784] opened 2022-04-06 11:26 UTC
I have the following step in my Maven build job to cache the CVE database created by the dependency-check plugin as it can take a while to download from scratch:

```
      - name: Cache CVE database for OWASP dependency-check
        uses: actions/cache@v3
        with:
          path: dependency-check-data
          key: "${{ runner.os }}-dependency-check-data-${{ hashFiles('**/nvdcve-1.1-modified.meta') }}"
          restore-keys: |
            ${{ runner.os }}-dependency-check-data-${{ hashFiles('**/nvdcve-1.1-modified.meta') }}
            ${{ runner.os }}-dependency-check-data-
```

The file I use to determine whether the cache should be updated is `dependency-check-data/nvdcve-1.1-modified.meta`. This file is only created during the build job, i.e. it is not part of the repository.

### First run

Obviously no cache hit.

In the post-build step the cache is created correctly, but GitHub actions says:

```
Cache saved with key: Linux-dependency-check-database-
```

That's not correct: it should save the cache with key `Linux-dependency-check-database-e6dd7c26af2b2d399adc976c9e67d9ae0e4013e1ef99f753a41fea199a11109e`.

Full debug output of the post-build step: https://gist.github.com/fransf-wtax/4f1c5c2aa5a153807bcd145aee281b33

### Second run

During cache restore i.e. before the build, the key will evaluate to `Linux-dependency-check-data-` which is fine because the plugin should match on prefixes so the most recent cache created in previous builds would be used.

Full debug output of the build step: https://gist.github.com/fransf-wtax/58e6f867603f076f874b2b4ceff7c25f

But after the build, when the cache is updated, GitHub Actions says:

```
##[debug]Cache state/key: Linux-dependency-check-data-
Cache hit occurred on the primary key Linux-dependency-check-data-, not saving cache.
```
This is not correct. The file matching `*/nvdcve-1.1-modified.meta` now exists, so it should re-evaluate the key `"${{ runner.os }}-dependency-check-data-${{ hashFiles('**/nvdcve-1.1-modified.meta') }}"` which would yield `Linux-dependency-check-data-a65b573939924c996fc1da62edc8e7c7c4cdf4ea9ec5b7a3c2b495ff37333213`, NOT the same as the cache that was restored and therefore not a cache hit.

Full output of the post-build step: https://gist.github.com/fransf-wtax/f69804e2f5ec2dd0c3b7577b618be3be

### Conclusion

It looks like GitHub is somehow not or incorrectly evaluating the cache key expression in the post-build step. If it would re-evaluate, I believe the cache action would work as expected.

**Comment by vsvipul** [comment] 2022-04-11 07:02
> The file I use to determine whether the cache should be updated is dependency-check-data/nvdcve-1.1-modified.meta. This file is only created during the build job, i.e. it is not part of the repository.

Try using `GITHUB_WORKSPACE` environment variable and giving an absolute file path in `hashFiles('**/nvdcve-1.1-modified.meta')`, which is the only problem I see. You can try running running ls in your workflow to see if you are using the correct path. There have been problems with using glob patterns like ** before as well.

**Comment by fransf-wtax** [comment] 2022-04-11 08:19
All the examples in the documentation use glob patterns starting with `**`, though. If that is unreliable, would be helpful to mention that in the docs and give more reliable examples.

Will try putting in an absolute path using `GITHUB_WORKSPACE`, see if that changes anything, and post findings here. Thanks!

**Comment by fransf-wtax** [comment] 2022-04-11 13:04
Tried with an absolute path, result is the same (see debug logs at end of this comment). 

The problem is not with `hashFiles` and how it uses globs, that part seems to be working just fine. The problem is the cache key that the post-job action is checking. It should be using the cache key but it seems to be using the restore key. Restore key should only be used for restore; the cache key should be used to update the cache. That seems to be broken.

```
##[debug]Evaluating condition for step: 'Post Cache CVE database for OWASP dependency-check'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Post Cache CVE database for OWASP dependency-check
##[debug]Loading inputs
##[debug]Evaluating: format('{0}-dependency-check-database-{1}', runner.os, hashFiles(env.dependency_check_database_meta))
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> '{0}-dependency-check-database-{1}'
##[debug]..Evaluating Index:
##[debug]....Evaluating runner:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'os'
##[debug]..=> 'Linux'
##[debug]..Evaluating hashFiles:
##[debug]....Evaluating Index:
##[debug]......Evaluating env:
##[debug]......=> Object
##[debug]......Evaluating String:
##[debug]......=> 'dependency_check_database_meta'
##[debug]....=> '/home/runner/work/***************/***************/dependency-check-data/nvdcache/nvdcve-1.1-modified.meta'
##[debug]Search root directory: '/home/runner/work/***************/***************'
##[debug]Search pattern: '/home/runner/work/***************/***************/dependency-check-data/nvdcache/nvdcve-1.1-modified.meta'
##[debug]Starting process:
##[debug]  File name: '/home/runner/runners/2.289.2/externals/node16/bin/node'
##[debug]  Arguments: '"/home/runner/runners/2.289.2/bin/hashFiles"'
##[debug]  Working directory: '/home/runner/work/***************/***************'
##[debug]  Require exit code zero: 'False'
##[debug]  Encoding web name:  ; code page: ''
##[debug]  Force kill process on cancellation: 'False'
##[debug]  Redirected STDIN: 'False'
##[debug]  Persist current code page: 'False'
##[debug]  Keep redirected STDIN open: 'False'
##[debug]  High priority process: 'False'
##[debug]Updated oom_score_adj to 500 for PID: 2003.
##[debug]Process started with process id 2003, waiting for process exit.
##[debug]Match Pattern: /home/runner/work/***************/***************/dependency-check-data/nvdcache/nvdcve-1.1-modified.meta
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::followSymbolicLinks 'false'
##[debug]::debug::implicitDescendants 'true'
##[debug]::debug::omitBrokenSymbolicLinks 'true'
##[debug]::debug::Search path '/home/runner/work/***************/***************/dependency-check-data/nvdcache/nvdcve-1.1-modified.meta'
##[debug]/home/runner/work/***************/***************/dependency-check-data/nvdcache/nvdcve-1.1-modified.meta
##[debug]Found 1 files to hash.
##[debug]Hash result: '7e136218789a65c03108167a7a6a278bab428b227fae60a72b34547b737961be'
##[debug]undefined
##[debug]STDOUT/STDERR stream read finished.
##[debug]STDOUT/STDERR stream read finished.
##[debug]Finished process 2003 with exit code 0, and elapsed time 00:00:00.0565783.
##[debug]..=> '7e136218789a65c03108167a7a6a278bab428b227fae60a72b34547b737961be'
##[debug]=> 'Linux-dependency-check-database-7e136218789a65c03108167a7a6a278bab428b227fae60a72b34547b737961be'
##[debug]Result: 'Linux-dependency-check-database-7e136218789a65c03108167a7a6a278bab428b227fae60a72b34547b737961be'
##[debug]Evaluating: format('{0}-dependency-check-database-
##[debug]', runner.os)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> '{0}-dependency-check-database-
##[debug]'
##[debug]..Evaluating Index:
##[debug]....Evaluating runner:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'os'
##[debug]..=> 'Linux'
##[debug]=> 'Linux-dependency-check-database-
##[debug]'
##[debug]Result: 'Linux-dependency-check-database-
##[debug]'
##[debug]Loading env
Post job cleanup.
##[debug]Cache state/key: Linux-dependency-check-database-
Cache hit occurred on the primary key Linux-dependency-check-database-, not saving cache.
##[debug]Node Action run completed with exit code 0
##[debug]Finishing: Post Cache CVE database for OWASP dependency-check
```

**Comment by vsvipul** [comment] 2022-04-12 06:14
@fransf-wtax Would be helpful if we can see the full workflow file? or atleast a public repo to reproduce this ?

> First run
Obviously no cache hit.
In the post-build step the cache is created correctly, but GitHub actions says:
```
Cache saved with key: Linux-dependency-check-database-
```
That's not correct: it should save the cache with key `Linux-dependency-check-database-e6dd7c26af2b2d399adc976c9e67d9ae0e4013e1ef99f753a41fea199a11109e`.

Here make sure when you are running the workflow first time, the cache step is run after the file which is to be hashed is created. Otherwise the hash will create an empty string which I feel is the case here.  

In reserveCache step we only use key, and not restore-keys as seen here in the code - https://github.com/actions/toolkit/blob/7654d97eb6c4a3d564f036a2d4a783ae9105ec07/packages/cache/src/internal/cacheHttpClient.ts#L143 .

**Comment by fransf-wtax** [comment] 2022-04-12 07:09
The relevant steps in the job are really only these:
```
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 17
          cache: maven
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v14
        with:
          repositories: '[{ "id": "nexus", "name": "Nexus", "url": "https://nexus.******.***/repository/maven-public/" }]'
          servers: '[{ "id": "nexus", "username": "github", "password": "${{ secrets.NEXUS_PASSWORD }}" }]'
      - name: Cache CVE database for OWASP dependency-check
        uses: actions/cache@v3
        with:
          path: dependency-check-data
          key: "${{ runner.os }}-dependency-check-database-${{ hashFiles('**/nvdcve-1.1-modified.meta') }}"
          restore-keys: |
            ${{ runner.os }}-dependency-check-database-
      - name: Build with Maven
        run: mvn clean verify sonar:sonar -Dsonar.host.url=https://sonar.*******.*** -Dsonar.login="${{ secrets.SONAR_TOKEN }}" -DdataDirectory=dependency-check-data
```

>Here make sure when you are running the workflow first time, the cache step is run after the file which is to be hashed is created. Otherwise the hash will create an empty string which I feel is the case here.

I think that's the problem here. The assumption is that the file based on which the cached files are hashed already exists _before_ the cache restore step. The examples use a `package.json` or `pom.xml`. But in my case I don't have something like that. I _do_ have a file in the set of files to be cached that on its own is an indicator of whether the set of files would have changed - but that file only exists after the cache step, since I obviously have to run the command that uses/creates the cached files after they've been restored.

I'd be happy for the cache to _always_ be updated in the post-job action if what I'm trying to do is not possible – but is that an option on this action?

**Comment by vsvipul** [comment] 2022-04-12 08:19
> I'd be happy for the cache to always be updated in the post-job action if what I'm trying to do is not possible – but is that an option on this action?

Nope, unfortunately, that is not currently supported and there are no plans to support in in the future as well unless there is a big ask from the community. 

What I can suggest you to do is to use some other cache key that signifies the change in file generated or use your own fork of the action and play around with it and see if you are able to achieve caching of this generated file. If yes, we might be able to review the PR with this added functionality.

Closing this issue for now. Might revisit in the future.

**Closed by vsvipul** 2022-04-12 08:19 UTC
Labels: question

**Comment by prncevince** [comment] 2022-06-01 15:33
Adding a simple boolean as a input to the action here to reevaluate in Post could be very helpful. 
e.g. the current default implementation `inputs:reevaluate:default:FALSE`.

I'm interested from the R programming community's point of view when it comes to using [code chunk caching](https://yihui.org/knitr/options/#cache) within the [{rmarkdown} package](https://bookdown.org/yihui/rmarkdown-cookbook/cache.html) & specifically [{knitr} chunk options](https://yihui.org/knitr/options/#cache). 

{knitr} creates & invalidates it's cache for each code chunk while the document is being rendered. One could invalidate the cache by simply hashing the file that the knitr code chunks are within, but this does not check that individual code chunks within the file have changed or that variable inputs to the chunks have changed (e.g. the reason to invalidate/bust the cache). A much simpler solution would be to hash all files within the knitr cache's output directory (most people will not version this - it's binary data).

A long way of saying: Time to learn some TypeScript 😉
