### ISSUE TITLE
Cache step rejected with "on schedule" workflows

### ISSUE THREAD

**Issue by lelegard** [actions/cache#174] opened 2020-02-04 17:08 UTC
Hi,

In a nightly build workflow ("on schedule"), I would like to avoid the rebuild when there was nothing new since last night, typically when there was no new commit.

My current solution is to store `github.sha` as a cache key (and empty cache content). In case of cache hit, the current commit was already used and there is no need to rebuild (the rebuild steps are conditioned by the cache hit).

I made some tests on `push` events to validate the workflow file and syntax. Of course, since this is a push, there is always a new commit. So, I moved to a schedule test. And it always fails.

Initial test, using `actions/cache@v1`: A warning is generated saying _"The event type schedule is not supported. Only push, pull_request events are supported at this time."_ The workflow is not aborted but there is never a cache hit and the build is always executed.

Workflow excerpt:
~~~
name: 10 mn test
on:
  schedule:
    - cron:  '*/10 * * * *'
jobs:
  windows:
    name: Windows test
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: Check cached commit
      id: cache-commit
      uses: actions/cache@v1
      with:
        key: ref-${{ github.sha }}
        path: ignored
~~~
The log shows:
~~~
Run actions/cache@v1
  with:
    key: ref-1f41d39611a534b282e8ca5c9e0d9235a595957b
    path: ignored
[warning]Event Validation Error: The event type schedule is not supported. Only push, pull_request events are supported at this time.
~~~

The same error is seen with `actions/cache@v1.1.0` (latest release as of today).

When using `actions/cache@master`, a fatal error terminates the workflow:
~~~
Run actions/cache@master
  with:
    key: ref-897795c9daa1210d2385c0bb4c8594233a4e2f5c
    path: ignored
##[error]File not found: 'D:\a\_actions\actions\cache\master\dist/restore/index.js'
~~~

So, there are two questions / problems:
- With the current master, there is a bug.
- "On schedule" workflows are repetitive by definition. And repetitive tasks often need identical contexts, making the use of the caching facility very useful. But it is not supported.

Is there anything wrong in my workflow? Any other solution?

**Comment by L-TChen** [comment] 2020-02-10 20:37
It seems like a duplicate of #63.

**Comment by joshmgross** [comment] 2020-02-16 04:03
We're tracking adding more event support with #63, but right now it's only supported for push and pull request events.

>When using actions/cache@master, a fatal error terminates the workflow

It's recommended to use this action from a release tag (ex. `@v1`) instead of the master branch. We will be adding the required js files to the master branch soon so that you can pin to master, but again it's not recommended.

**Closed by joshmgross** 2020-02-16 04:03 UTC
