### ISSUE TITLE
Feature request: Ability to store cache if build fails

### ISSUE THREAD

**Issue by sergeyzwezdin** [actions/cache#272] opened 2020-04-24 17:41 UTC
This is for the docs:
> If the job completes successfully, the action creates a new cache with the contents of the path directory.

In some cases it could be useful to store cache key even if some build steps are failed. Could you please define a new option that allows us to use such behavior?

**Comment by iBug** [comment] 2020-05-03 03:45
Or maybe go around and allow users to specify where to insert the "save cache" step for better control, e.g., save cache between step N and step N+1, so when step N fails the cache is discarded while the failure of step N+1 doesn't affect cache saving.

**Comment by jakemwood** [comment] 2020-06-29 06:10
@sergeyzwezdin In case anyone finds this via search, this is relatively easy to do. You can fork this repo, remove one line in `action.yml`, and voila! Here is my own repo / commit that does this: https://github.com/jakemwood/cache/commit/d8a0d1ca35dc43ea043cfd82c5800c56a1e587a7

**Comment by sergeyzwezdin** [comment] 2020-06-29 07:09
@jakemwood I don’t want to support my own repo for this 🙂

**Comment by ioquatix** [comment] 2020-08-12 01:34
We are investigating using `RuboCop` and if there are lint failures, the cache would not be updated, which doesn't make sense. In fact, I can't think of many situations where just because a build step fails, the cache should not be updated... At the very least, can we expose this as a configuration option?

**Comment by ruohola** [comment] 2021-04-17 22:15
Duplicate of https://github.com/actions/cache/issues/92 right?

**Comment by teohhanhui** [comment] 2021-12-31 22:10
@iBug:
> Or maybe go around and allow users to specify where to insert the "save cache" step for better control, e.g., save cache between step N and step N+1, so when step N fails the cache is discarded while the failure of step N+1 doesn't affect cache saving.

That's #46 :smile:

**Comment by kotewar** [comment] 2022-11-17 07:50
I was wondering if anybody tried [continue-on-error](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) input in their job. 

Example [workflow](https://github.com/kotewar/test-continue-on-error-for-cache/actions/runs/3486334557/workflow#L29) and [run](https://github.com/kotewar/test-continue-on-error-for-cache/actions/runs/3486334557/jobs/5832702504#step:6:5)

I was able to save cache despite of the induced error as the job exits silently and moves on to the next step.

**Comment by wmertens** [comment] 2022-11-17 09:36
@kotewar the cache save step should run but the workflow as a whole should fail. Afaik there's no such setting.

**Comment by kotewar** [comment] 2022-11-17 10:31
@wmertens , do you mean something like [this](https://github.com/kotewar/test-continue-on-error-for-cache/actions/runs/3487439646/jobs/5835067602)?

<img width="636" alt="Screenshot 2022-11-17 at 4 00 59 PM" src="https://user-images.githubusercontent.com/98868223/202423043-df6bd298-f017-4a49-9be3-3e7484f39831.png">

**Comment by wmertens** [comment] 2022-11-18 16:27
@kotewar, no, the job itself should fail. Somehow the status of "Induce error" should bypass "post run kotewar".
Currently, your "Build Test" will always be green.

**Comment by kotewar** [comment] 2022-12-27 16:04
We have released a [save](https://github.com/actions/cache/tree/main/restore) action that can run always if passed with condition `if: always()`. This can be used with [restore](https://github.com/actions/cache/tree/main/restore) action that does the job of restoring the cache.

We believe this solves your use case, hence closing this issue. Feel free to reopen if need be.

**Closed by kotewar** 2022-12-27 16:04 UTC
Labels: feature request, area:granular-control
