### ISSUE TITLE
Cache not posting

### ISSUE THREAD

**Issue by tmpellerito** [actions/cache#656] opened 2021-10-07 15:41 UTC
A few days ago, my workflows were working fine, without changing them, now they are blowing up when attempting to get a cache that was expected to be posted.

## Posting the cache:
- name: Cache repo and maven build
      uses: actions/cache@v2
      with:
        key: maven-build-${{ github.sha }}
        path: ~/

yields:
![image](https://user-images.githubusercontent.com/63749185/136417734-9cd827b0-42f6-4721-acbb-2d330439fda1.png)

## A subsequent attempt to get the cache:
    - name: Get maven cache
      uses: actions/cache@v2
      with:
        key: maven-build-${{ github.sha }}
        path: ~/

yields:
![image](https://user-images.githubusercontent.com/63749185/136417953-a4f715cc-1f70-4eec-8f93-6a8eaa78927c.png)

**Comment by Phantsure** [comment] 2022-04-18 11:25
@tmpellerito Are you still facing this issue?

**Comment by Phantsure** [comment] 2022-05-02 11:08
@tmpellerito Can you confirm if you are getting this issue now?

**Comment by dopplershift** [comment] 2022-06-12 03:58
Dupe of #689 (which is fixed for me now in v3)?

**Comment by vsvipul** [comment] 2022-06-17 17:08
Closing as duplicate.

**Closed by vsvipul** 2022-06-17 17:08 UTC
