### ISSUE TITLE
Warning: Failed to save: "C:\Program failed with error

### ISSUE THREAD

**Issue by andreasabel** [actions/cache#1092] opened 2023-01-27 12:28 UTC
Thanks for the great work on actions!

It seems that the `save` action does not respect quotation when printing a warning.  E.g. [I can see](https://github.com/agda/agda/actions/runs/4023916953/jobs/6915349140#step:13:17):
```
Warning: Failed to save: "C:\Program failed with error: ...
```
Full output:
```
Run actions/cache/save@v3
...
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/agda/agda --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
/usr/bin/tar: cache.tzst: Cannot write: Broken pipe
/usr/bin/tar: Child returned status 127
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
Warning: Cache save failed.
```

(Not a big issue, but it severs trust.)

**Comment by mmuetzel** [comment] 2023-02-10 15:07
Maybe a duplicate of #1073?
Are you using Cygwin? The error message looks similar to the one in that issue.

**Comment by andreasabel** [comment] 2023-02-11 10:55
I don't think that the GitHub virtual environments use Cygwin.  For details what I have been using, see https://github.com/agda/agda/actions/runs/4023916953/jobs/6915349140#step:1:8
>  Image: windows-2022
>  Version: 20230123.1
>  Included Software: https://github.com/actions/runner-images/blob/win22/20230123.1/images/win/Windows2022-Readme.md
>  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20230123.1

**Comment by mmuetzel** [comment] 2023-02-11 12:23
It looks like you are adding the MSYS2 `usr/bin` path to the `PATH` variable here:
https://github.com/agda/agda/actions/runs/4023916953/workflow#L52

The MSYS2 environment is approximately the same as Cygwin. Git for Windows is a derivative of MSYS2 and brings its own Cygwin-derived parts. Since the changes pointed out in the other issue, the cache action uses `tar` from Git for Windows.
It might be that the Cygwin-derived parts of Git for Windows do not only conflict with Cygwin proper, but also with the (Cygwin-derived) MSYS2 runtime environment.
If that case, this issue is caused by a slightly different constellation of conflicting runtime environments. But it is failing for the same reason as #1073.

**Comment by andreasabel** [comment] 2023-02-12 08:33
@mmuetzel : Thank you for the explanation!  I appreciate such insights into the Windows virtual environment!  (It may help me with another workflow I am struggling to get right.)

Maybe I need to apologize that I didn't make my issue report clear enough.  My impression was the failure of the cache action is erratic ("Broken pipe"), at least it didn't persist.  I didn't raise the issue about this "Heisenbug".

The reason I raised this issue is that the action does not produce the warning in a sound way.
> It seems that the save action does not respect quotation when printing a warning. 

It looks like that the code producing the warning breaks a command simply by spaces, assuming the first word would be the executable.  However, this fails if the path of the executable contains spaces.  Those are guarded by `"` quotes, but the code producing the warning does not respect these quotes.

**Comment by andreasabel** [comment] 2023-02-12 08:56
@mmuetzel wrote
> It looks like you are adding the MSYS2 `/usr/bin` path to the `PATH` variable here:

Investigating this again, you are right:  This actually breaks the cache action.  Not just "erratic" as I claimed, or a "Heisenbug".
So I have to debug my workflow, taking #1073 into account.

**Comment by Phantsure** [comment] 2023-03-01 09:52
After changes on git-for-windows side this issue seems to be resolved: https://github.com/Phantsure/agda/actions/runs/4302024885/jobs/7499982717#step:21:2
Closing this issue for now. Please re-open if issue exists for anyone

**Closed by Phantsure** 2023-03-01 09:52 UTC

**Comment by atri-dastidar-snkeos** [comment] 2023-04-05 14:20
Issue still exists for me with git version `2.40.0.windows.1` installed on a self-hosted runner with Windows Server 2019.

Log from post cache job:

```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tgz --exclude cache.tgz -P -C C:/actions-runner/_work/healthcare-platform/healthcare-platform --files-from manifest.txt --force-local -z
/bin/sh: line 1: gzip: command not found
/usr/bin/tar: cache.tgz: Cannot write: Broken pipe
/usr/bin/tar: Child returned status 127
/usr/bin/tar: Error is not recoverable: exiting now
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```

@Phantsure 
Can this issue be reopened? Do you need more info?

**Comment by Phantsure** [comment] 2023-04-05 15:27
Looks like no compression tool, i.e. zstd or gzip, is not found in path.
Please check.

P.S. Recent layoffs has impacted me so might not be able attend to all
replies here.

**Comment by prplecake** [comment] 2023-04-05 22:52
> Issue still exists for me with git version `2.40.0.windows.1` installed on a self-hosted runner with Windows Server 2019.

Likewise. My post job log looks identical.
