### ISSUE TITLE
v3.0.6 introduced dependency on zstdmt (not just zstd) for cache creation, fails on Windows

### ISSUE THREAD

**Issue by rfay** [actions/cache#891] opened 2022-08-09 00:53 UTC
As of v3.0.6 this apparently requires zstdmt, not just zstd, which is a major departure. I have not found any Windows binaries for zstdmt. I'm not sure it's available elsewhere either. 

This is what happens:

`##[debug]Archive Path: C:\drud-actions-runner\_work\_temp\ff5371eb-5f15-4474-8084-5df62fc397fa\cache.tzst
"C:\Program Files\Git\usr\bin\tar.exe" --posix --use-compress-program zstdmt -cf cache.tzst --exclude cache.tzst -P -C C:/drud-actions-runner/_work/ddev/ddev --files-from manifest.txt --force-local
/bin/sh: zstdmt: command not found
/usr/bin/tar: cache.tzst: Cannot write: Broken pipe
`

It was already hard enough to get zstd onto Windows... It's sad to break things now by changing the tar compression format even father. 

Previous instructions for getting zstd into a Windows machine were at https://github.com/actions/cache/issues/580#issuecomment-1165839728

**Comment by kotewar** [comment] 2022-08-09 12:55
Hi @rfay 
Thanks for reporting this. We are aware of the issue with Windows machine and the work is already in progress for the same. 

The issue being tracked [here](https://github.com/actions/cache/issues/888#issuecomment-1208234966).

**Comment by pdotl** [comment] 2022-08-22 09:38
Hi @rfay, the tar compression(zstd) on Windows while using the above workaround should now work. Please test and let us know if the issue is now resolved.

**Comment by kleisauke** [comment] 2022-08-22 09:53
I can confirm that v3.0.8 fixes the issue, see e.g. commit https://github.com/kleisauke/wasm-vips/commit/50c7d00b8e22986a096aab8c55737bfca245c1b8.

**Comment by pdotl** [comment] 2022-08-22 09:57
Closing the issue since a fix has been deployed and tested. Feel free to re-open if recurs.

**Closed by pdotl** 2022-08-22 09:57 UTC
Labels: duplicate, area:compression

**Comment by rfay** [comment] 2022-08-23 00:34
@pdotl I assume we still have to do the bizarre installation of zstd on windows self-hosted runners still, true? Did that make it into docs?

**Comment by pdotl** [comment] 2022-08-25 13:10
@rfay we are adding the above workaround to the docs and will also document installation of `zstd` for windows self-hosted runners. If you are only using Windows self-hosted runners and not doing any cross-os caching as above, `zstd` is not required. The action will fallback to using `gzip` if it does not find `zstd` installed.

**Comment by rfay** [comment] 2022-08-25 18:53
Yeah, I do cross-OS caching.
