### ISSUE TITLE
v4.0 save always not working

### ISSUE THREAD

**Issue by DanMawdsleyBA** [actions/cache#1315] opened 2024-01-30 09:39 UTC
I have setup the save always to true such that the cache step should always fail even if one of the tasks fail. See screenshots below:
Save always set to true in step:
![image](https://github.com/actions/cache/assets/134394384/b13b6213-1e7f-4ac0-8af6-76de59765fe0)

Then further in the job a step fails but the post cache step is not run unlike the post repositry setup:
![image](https://github.com/actions/cache/assets/134394384/1dfe308e-7b7c-4c6a-a15b-8ef1e1f626c2)

Related to 
https://github.com/actions/cache/pull/1242

**Comment by DanMawdsleyBA** [comment] 2024-01-30 09:51
For context this is how I did save cache in v3:

![image](https://github.com/actions/cache/assets/134394384/dbc36860-71cf-405f-842e-ad09166d414a)

**Comment by SukkaW** [comment] 2024-02-08 15:06
I am also facing this issue. With `save-always: true`, the `Post Cache` is still skipped if the previous build step has failed:

<img width="498" alt="image" src="https://github.com/actions/cache/assets/40715044/3c7c86c4-6815-481d-a9e9-f956fedd9f1f">

**Comment by sascha-wolf** [comment] 2024-02-27 07:49
We're observing the same issue. It just doesn't seem to work as documented.
![image](https://github.com/actions/cache/assets/2647626/8bf6ef04-adac-4d53-8e24-b5d506d3d295)

**Comment by joshmgross** [comment] 2024-06-12 20:14
👋 Thank you for the bug report and apologies for the lack of a timely response.

As I shared in https://github.com/actions/cache/pull/1325#discussion_r1636968780, I do not believe this is a feature we can support in this action today due to limitations in what's possible in `post-if` expressions.

As @DanMawdsleyBA shared above, if you want to override the `post-if` behavior of the default cache action you can utilize the separate `actions/cache/save` and `actions/cache/restore`. This sort of granularity is what these actions were originally intended for - #1035.

That might look something like:

```yaml
name: Always Caching Primes

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          path/to/dependencies
          some/other/dependencies
        key: ${{ runner.os }}-primes

    # Intermediate workflow steps

    - name: Always Save Primes 
      id: cache-primes-save
      if: always() && steps.cache-primes-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          path/to/dependencies
          some/other/dependencies
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
```

Given that `save-always` never worked, I believe it would make the most sense to deprecate that action input and remove it in a future version release. It's not something we can confidently support long term with the current features of `post-if` - any workarounds we implement today are likely to break in the future if they're relying on undocumented behavior. #1242 should not have been approved or merged without sufficient testing from us to validate that it was working as intended.


My current plan is to:
1. Deprecate `save-always` in the current major version to indicate to users that it's not working as intended
2. Document in the README how to support this scenario with `actions/cache/save`
3. Remove `save-always` in the next major version

I realize this won't likely won't be a popular course of action, but I believe it's best for the long term maintainability of this action. I'd appreciate any and all feedback here, especially around the propose workaround if scenarios where it might not work.

**Comment by ruffsl** [comment] 2024-06-18 02:51
> Document in the README how to support this scenario with `actions/cache/save`

@joshmgross , is there more that should be added to specified here?

- https://github.com/actions/cache/blob/main/save/README.md#always-save-cache

**Comment by joshmgross** [comment] 2024-06-18 21:29
> > Document in the README how to support this scenario with `actions/cache/save`
> 
> [@joshmgross](https://github.com/joshmgross) , is there more that should be added to specified here?
> 
> * https://github.com/actions/cache/blob/main/save/README.md#always-save-cache

I was thinking it'd make sense to include the `cache-hit` output in that `if` conditional. The dedicated save cache action won't have access to the intra action state used by the restore step to indicate if the save is necessary.

https://github.com/actions/cache/blob/0c45773b623bea8c8e75f6c82b208c3cf94ea4f9/src/saveImpl.ts#L46-L48

**Comment by fulldecent** [comment] 2024-09-09 20:21
Here is the current documentation with the workaround.

And it does NOT recommend using save-always

https://github.com/actions/cache/blob/main/caching-strategies.md#saving-cache-even-if-the-build-fails

**Comment by joshmgross** [comment] 2024-10-07 17:38
`save-always` has been deprecated as it's not something we can support at this time. #1452 

See https://github.com/actions/cache/issues/1315#issuecomment-2163822166 for more details.

**Closed by joshmgross** 2024-10-07 17:38 UTC
Labels: bug
